### ISSUE TITLE
The promise was rejected with reason: The path of a URI with an authority must start with a slash &quot;/&quot; or be empty 

### ISSUE THREAD

**Issue by etienne-combustible** [NicklasWallgren/instagram-api#51]
Hi,
I'm having an issue after a fresh install with the authenticate_using_password example.
```
**Fatal error**: Uncaught Instagram\SDK\Exceptions\InstagramException: The promise was rejected with reason: The path of a URI with an authority must start with a slash "/" or be empty in /vendor/nicklasw/instagram-api/src/Utils/PromiseUtils.php:58 
Stack trace: 
#0 /vendor/nicklasw/instagram-api/src/Traits/MakeAccountRequestAccessible.php(33): Instagram\SDK\Utils\PromiseUtils::wait(Object(GuzzleHttp\Promise\Promise)) 
#1 /index.php(9): Instagram\SDK\Instagram->login('XXXXXXXX', 'XXXXXXXX') 
#2 {main} thrown in /vendor/nicklasw/instagram-api/src/Utils/PromiseUtils.php on line 58
```

Am I missing something ?

**Comment by NicklasWallgren** [comment]
Hey, it seems like https://github.com/NicklasWallgren/instagram-api/pull/45 introduced an issue with Guzzle 7.x. 

It should be fixed in https://github.com/NicklasWallgren/instagram-api/releases/tag/v0.10.3
