### ISSUE TITLE
Uncaught Instagram\SDK\Exceptions\RateLimitResponseException

### ISSUE THREAD

**Issue by 89z** [NicklasWallgren/instagram-api#57]
Using this program:

~~~php
<?php
require_once 'autoload.php';
use Instagram\SDK\Instagram;
$instagram = Instagram::builder()->build();
$instagram->login('srpen6', 'PASSWORD');
~~~

I get this result:

~~~
Fatal error: Uncaught Instagram\SDK\Exceptions\RateLimitResponseException:
Please wait a few minutes before you try again. in
D:\Desktop\vendor\nicklasw\instagram-api\src\Response\Serializers\AbstractResponseSerializer.php:134
Stack trace:
#0 D:\Desktop\vendor\nicklasw\instagram-api\src\Response\Serializers\AbstractResponseSerializer.php(59): Instagram\SDK\Response\Serializers\AbstractResponseSerializer::toException('rate_limit_erro...', Object(Instagram\SDK\Response\Responses\User\SessionResponse))
#1 D:\Desktop\vendor\nicklasw\instagram-api\src\Response\Serializers\User\LoginResponseSerializer.php(59): Instagram\SDK\Response\Serializers\AbstractResponseSerializer->decode(Object(GuzzleHttp\Psr7\Response), Object(Instagram\SDK\Client\Client))
#2 D:\Desktop\vendor\nicklasw\instagram-api\src\Client\Client.php(174): Instagram\SDK\Response\Serializers\User\LoginResponseSerializer->decode(Object(GuzzleHttp\Psr7\Response), Object(Instagram\SDK\Client\Client))
#3 D:\Desktop\vendor\nicklasw\instagram-api\src\Utils\PromiseUtils.php(34): Instagram\SDK\Client\Client->Instagram\SDK\Client\{closure}()
#4 D:\Desktop\vendor\guzzlehttp\promises\src\TaskQueue.php(48): Instagram\SDK\Utils\PromiseUtils::Instagram\SDK\Utils\{closure}()
#5 D:\Desktop\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(158): GuzzleHttp\Promise\TaskQueue->run()
#6 D:\Desktop\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(183): GuzzleHttp\Handler\CurlMultiHandler->tick()
#7 D:\Desktop\vendor\guzzlehttp\promises\src\Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#8 D:\Desktop\vendor\guzzlehttp\promises\src\Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#9 D:\Desktop\vendor\guzzlehttp\promises\src\Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#10 D:\Desktop\vendor\guzzlehttp\promises\src\Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#11 D:\Desktop\vendor\guzzlehttp\promises\src\Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#12 D:\Desktop\vendor\guzzlehttp\promises\src\Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#13 D:\Desktop\vendor\guzzlehttp\promises\src\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#14 D:\Desktop\vendor\nicklasw\instagram-api\src\Utils\PromiseUtils.php(54): GuzzleHttp\Promise\Promise->wait()
#15 D:\Desktop\vendor\nicklasw\instagram-api\src\Traits\MakeAccountRequestAccessible.php(33): Instagram\SDK\Utils\PromiseUtils::wait(Object(GuzzleHttp\Promise\Promise))
~~~

**Comment by NicklasWallgren** [comment]
Hey, your account/ip probably got flagged by the anti bot protection.

You either need to wait until the flag has been lifted, try with another account or use a proxy.

It's important that you re-use your previous sessions, otherwise you will be an easy target by the anti bot protection.
