### ISSUE TITLE
error

### ISSUE THREAD

**Issue by uzleon** [NicklasWallgren/instagram-api#85]
Fatal error: Uncaught Instagram\SDK\Exceptions\UnexpectedResponseException: Retrieved unexpected response {"message":"Sorry, there was a problem with your request.","status":"fail"} in /var/www/abdox/data/www/9k.uz/vendor/nicklasw/instagram-api/src/Response/Serializers/AbstractResponseSerializer.php:103 Stack trace: #0 /var/www/abdox/data/www/9k.uz/vendor/nicklasw/instagram-api/src/Response/Serializers/AbstractResponseSerializer.php(47): Instagram\SDK\Response\Serializers\AbstractResponseSerializer::handleUnexpectedHttpResponse(Object(GuzzleHttp\Psr7\Response)) #1 /var/www/abdox/data/www/9k.uz/vendor/nicklasw/instagram-api/src/Response/Serializers/User/LoginResponseSerializer.php(59): Instagram\SDK\Response\Serializers\AbstractResponseSerializer->decode(Object(GuzzleHttp\Psr7\Response), Object(Instagram\SDK\Client\Client)) #2 /var/www/abdox/data/www/9k.uz/vendor/nicklasw/instagram-api/src/Client/Client.php(176): Instagram\SDK\Response\Serializers\User\LoginResponseSerializer->decode(Object(GuzzleHttp\Psr7\Response), Object(Instagram\SDK\Client\Client)) #3 /var/www/abdox/data/www/9k.uz/vendor/nicklasw/instagram-api/src/Utils/PromiseUtils.php(34): Instagram\SDK\Client\Client->Instagram\SDK\Client\{closure}() #4 /var/www/abdox/data/www/9k.uz/vendor/guzzlehttp/promises/src/TaskQueue.php(52): Instagram\SDK\Utils\PromiseUtils::Instagram\SDK\Utils\{closure}() #5 /var/www/abdox/data/www/9k.uz/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(159): GuzzleHttp\Promise\TaskQueue->run() #6 /var/www/abdox/data/www/9k.uz/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(185): GuzzleHttp\Handler\CurlMultiHandler->tick() #7 /var/www/abdox/data/www/9k.uz/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Handler\CurlMultiHandler->execute(true) #8 /var/www/abdox/data/www/9k.uz/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn() #9 /var/www/abdox/data/www/9k.uz/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending() #10 /var/www/abdox/data/www/9k.uz/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList() #11 /var/www/abdox/data/www/9k.uz/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending() #12 /var/www/abdox/data/www/9k.uz/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList() #13 /var/www/abdox/data/www/9k.uz/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending() #14 /var/www/abdox/data/www/9k.uz/vendor/nicklasw/instagram-api/src/Utils/PromiseUtils.php(54): GuzzleHttp\Promise\Promise->wait() #15 /var/www/abdox/data/www/9k.uz/vendor/nicklasw/instagram-api/src/Traits/MakeAccountRequestAccessible.php(33): Instagram\SDK\Utils\PromiseUtils::wait(Object(GuzzleHttp\Promise\Promise)) #16 /var/www/abdox/data/www/9k.uz/mm.php(8): Instagram\SDK\Instagram->login('ddddddddd', 'ddddddddd') #17 {main} thrown in /var/www/abdox/data/www/9k.uz/vendor/nicklasw/instagram-api/src/Response/Serializers/AbstractResponseSerializer.php on line 103

**Comment by uzleon** [comment]
Can you help me on how to fix this error?
