### ISSUE TITLE
Uncaught Instagram\SDK\Exceptions\ApiResponseException in src/Response/Serializers/AbstractResponseSerializer.php:137

### ISSUE THREAD

**Issue by JerichoWord** [NicklasWallgren/instagram-api#86]
i cannot login to instagrame

<html>
<body>

<br />
--
  | <b>Fatal error</b>:  Uncaught Instagram\SDK\Exceptions\ApiResponseException in /www/wwwroot/8851/src/Response/Serializers/AbstractResponseSerializer.php:137
  | Stack trace:
  | #0 /www/wwwroot/8851/src/Response/Serializers/AbstractResponseSerializer.php(59): Instagram\SDK\Response\Serializers\AbstractResponseSerializer::toException()
  | #1 /www/wwwroot/8851/src/Response/Serializers/User/LoginResponseSerializer.php(59): Instagram\SDK\Response\Serializers\AbstractResponseSerializer-&gt;decode()
  | #2 /www/wwwroot/8851/src/Client/Client.php(177): Instagram\SDK\Response\Serializers\User\LoginResponseSerializer-&gt;decode()
  | #3 /www/wwwroot/8851/src/Utils/PromiseUtils.php(34): Instagram\SDK\Client\Client-&gt;Instagram\SDK\Client\{closure}()
  | #4 /www/wwwroot/8851/vendor/guzzlehttp/promises/src/TaskQueue.php(48): Instagram\SDK\Utils\PromiseUtils::Instagram\SDK\Utils\{closure}()
  | #5 /www/wwwroot/8851/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(118): GuzzleHttp\Promise\TaskQueue-&gt;run()
  | #6 /www/wwwroot/8851/vendor/guzzlehttp/guzzle/src/Handler/CurlMu in <b>/www/wwwroot/8851/src/Response/Serializers/AbstractResponseSerializer.php</b> on line <b>137</b><br />

</body>
</html>

**Comment by JerichoWord** [comment]
<?php

declare(strict_types=1);

use Instagram\SDK\Client\Adapters\PromiseAdapter;
use Instagram\SDK\Instagram;

require_once __DIR__ . '/../vendor/autoload.php';

$instagram = Instagram::builder()->setProxyUri('192.168.5.25:7890')->build();

$response = $instagram->login('wqa', 'Tdwa');

**Comment by bad-robo** [comment]
hi 
php my cpanel : 7.4 

i get proxy  this site : 
https://hidemy.io/en/proxy-list/?type=s#list

and problem

Fatal error: Uncaught Instagram\SDK\Exceptions\InstagramException: cURL error 7: Failed to connect to 35.220.175.141 port 8081: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://i.instagram.com/api/v1/si/fetch_headers/ in /home3/nimlxueu/public_html/insta/vendor/nicklasw/instagram-api/src/Utils/PromiseUtils.php:58 Stack trace: #0 /home3/nimlxueu/public_html/insta/vendor/nicklasw/instagram-api/src/Traits/MakeAccountRequestAccessible.php(33): Instagram\SDK\Utils\PromiseUtils::wait(Object(GuzzleHttp\Promise\Promise)) #1 /home3/nimlxueu/public_html/insta/user.php(13): Instagram\SDK\Instagram->login('se#####', '####00') #2 {main} thrown in /home3/nimlxueu/public_html/insta/vendor/nicklasw/instagram-api/src/Utils/PromiseUtils.php on line 58

**Comment by bad-robo** [comment]
**Fixing the above problem (for others):**

This problem is due to the blocked ip host or filter.
Your problem will be solved by using a private (or healthy) proxy.
